# Generated by Django 5.0.1 on 2024-02-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatDoAnBEApp', '0004_alter_dish_chuthich'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dish',
            field=models.ManyToManyField(related_name='orders', to='DatDoAnBEApp.dish'),
        ),
    ]
