# Generated by Django 5.0.1 on 2024-02-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatDoAnBEApp', '0007_alter_order_ten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ten',
            field=models.CharField(default='Hoa Don', max_length=50),
        ),
    ]
