# Generated by Django 5.0.1 on 2024-02-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatDoAnBEApp', '0008_alter_order_ten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m'),
        ),
    ]
