# Generated by Django 5.0.1 on 2024-02-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatDoAnBEApp', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SHOP', 'Shop')], max_length=7),
        ),
    ]
