# Generated by Django 5.0.1 on 2024-02-18 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatDoAnBEApp', '0011_alter_user_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ten',
        ),
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shop', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
