# Generated by Django 5.0.1 on 2024-02-19 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatDoAnBEApp', '0012_remove_order_ten_alter_shop_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='DatDoAnBEApp.dish')),
                ('parentComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childComments', to='DatDoAnBEApp.comment')),
            ],
        ),
    ]
