# Generated by Django 5.0.1 on 2024-02-19 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatDoAnBEApp', '0014_alter_comment_parentcomment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tongTien',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='userConsumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='userShop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='DatDoAnBEApp.shop'),
        ),
    ]
