# Generated by Django 5.0.1 on 2024-02-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatDoAnBEApp', '0016_alter_order_ngayorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ngayOrder',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
