# Generated by Django 5.0.1 on 2024-02-21 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatDoAnBEApp', '0017_alter_order_ngayorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(default='Unknown', max_length=255)),
                ('shopUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='DatDoAnBEApp.shop')),
            ],
        ),
    ]
