# Generated by Django 5.0.1 on 2024-02-21 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatDoAnBEApp', '0019_dish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='shopUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to=settings.AUTH_USER_MODEL),
        ),
    ]
