# Generated by Django 5.0.1 on 2024-02-24 05:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatDoAnBEApp', '0021_remove_order_dish_datmon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ngayOrder',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
    ]
